### ISSUE TITLE
 the bottom sediment of Flake

### ISSUE THREAD

**Issue by ShenBoms** [aemon-j/LakeEnsemblR#287]
I want to switch off the bottom sediment of Flake in LakeEnsemblR, but I can't find the relevant code.

**Comment by JFeldbauer** [comment]
Hello,
using the LakeEnsemblR configuration file (usually called LakeEnsemblR.yaml) you can set model specific parameters in the section `model_parameters:` For FLake this might look like this:

```yaml
model_parameters:
   FLake:                                       # FLake specific parameters
      depth_bs_lk: 0.0                         
```

so you need to find the parameter in the FLake config file that controls bottom sediment (might be `depth_bs_lk`, but I am not sure if this is what you want) and add it with the desired value. I hope this helps
