### ISSUE TITLE
Add option to calibrate model-specific parameters

### ISSUE THREAD

**Issue by jorritmesman** [aemon-j/LakeEnsemblR#40]
Currently, it is hard-coded that wind_factor, swr_factor, and lw_factor (or corresponding parameters) are calibrated. We should add the possibility for users to choose the parameters they want to calibrate, and between what ranges. 

Not all parameters are shared between all models (e.g. a_seiche in Simstrat, or g1/g2 in GOTM).

**Comment by tadhg-moore** [comment]
I was imagining to include an argument to specify 'met', 'model' or 'both'. This would allow ways to partition out uncertainty according to met and model and measure the sensitivity of each.

**Comment by jorritmesman** [comment]
That would be a good idea. My first thought was to make a calibration config file (as in GOTM/Simstrat) and make all specifications there (if we prefer, we can include it in the existing master config file as well). We could make separate groups (met/FLake/GOTM/GLM/Simstrat) there.

**Comment by tadhg-moore** [comment]
The reason why I would like to include 'met', 'model' or 'both' is because the 'met' parameters are simple scaling factors that we can apply direct to the met file and don't have to interact with the model configuration. This is because only GLM and GOTM have parameters that allow scaling within the model config. Then calibrating model specific parameters would be calibrating parameters that are model specific, 'k_min' in GOTM, 'a_seiche' in Simstrat etc. if you calibrated each separately then you can assess the sensitivity and use that prior information to inform your calibration when you include both in the same calibration.

**Comment by JFeldbauer** [comment]
I started working on this and have a suggestion for the master controll yaml file:

```
LHS:
   parameter:
     - wind_factor
     - swr_factor
     - lw_factor
   upper: 
     - 2
     - 1.5
     - 1.5
   lower:
     - 0.5
     - 0.5
     - 0.5
   name_GOTM:
     - wind_factor
     - swr_factor
     - lw_factor
   name_GLM:
     - wind_factor
     - swr_factor
     - lw_factor
   name_Simstrat: 
     - wind_factor
     - swr_factor
     - lw_factor
   name_FLake: 
     - wind_factor
     - swr_factor
     - lw_factor
   meteo:
      scale_wind_up: 2
      scale_wind_low: 0.5
      scale_air_temp_up: 1.5
      scale_air_temp_low: 0.5
```

**Comment by tadhg-moore** [comment]
Why do you need the `name_model` parts?

I thought that this would be enough:

```
LHS:
   parameter:
     - wind_factor
     - swr_factor
     - lw_factor
   upper: 
     - 2
     - 1.5
     - 1.5
   lower:
     - 0.5
     - 0.5
     - 0.5
```
Because these would be globally applied to the met file and for the model in the `run_LHS()` function. I also have not tested the `gotmtools::get_yaml_value()` on lists in a yaml file so this will also probably have to be adjusted.
